#include <iostream>
#include <vector>

/*
Problem 2:
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

int main()
{
    int n = 4000000;
    int sum = 0, nextTerm = 0;
    std::vector<int> fib;
    fib.push_back(0);
    fib.push_back(1);
    int newNumber = fib[fib.size() - 1] + fib[fib.size() - 2];
    while (newNumber < n)
    {
        fib.push_back(newNumber);
        if (newNumber % 2 == 0)
        {
            sum += newNumber;
        }
        newNumber = fib[fib.size() - 1] + fib[fib.size() - 2];
    }
    std::cout << sum << '\n';
}